/**
 * Emits the Go mirror of src/generated/jawcode-model-metadata.ts.
 *
 * Source choice (devlog/_plan/260729_go_cost_parity_stability/020): the Go bundle
 * is derived from the COMMITTED TypeScript artifact — the same bytes the TS
 * runtime reads — so the two runtimes cannot drift apart. Deriving from the
 * external jawcode checkout instead would let each side regenerate on its own
 * schedule and silently disagree on price.
 *
 * Model rows come from the module's exported accessors so that rowToMetadata's
 * null handling is applied once, in one place. Two values are module-private and
 * need their own paths: PROVIDER_ALIASES (taken from its exported upstream
 * deriveJawcodeAliases, then cross-checked) and COST_VENDOR_PRIORITY (parsed from
 * the artifact, order preserved because order decides which vendor wins).
 */
import { execFileSync } from "node:child_process";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { deriveJawcodeAliases } from "../src/providers/derive";
import { listJawcodeModelMetadata } from "../src/generated/jawcode-model-metadata";

const sourcePath = resolve(process.cwd(), "src/generated/jawcode-model-metadata.ts");
const outPath = resolve(process.cwd(), "go/internal/jawcode/metadata.go");
const source = readFileSync(sourcePath, "utf-8");

/** Anything that yields an empty bundle must abort: a silently empty price table
 *  still compiles and still serves, it just prices nothing. */
function must<T>(value: T | null | undefined, message: string): T {
  if (value === null || value === undefined) throw new Error(message);
  return value;
}

// Provider bundle names. Deliberately permissive (`[^"]+`): a narrower class
// would silently skip a future key containing a dot, underscore, or capital.
const providers = [...source.matchAll(/^  "([^"]+)": \[/gm)].map(m => m[1]);
if (providers.length === 0) throw new Error("provider scan matched nothing — generated format changed");

// Order is the contract: findJawcodeCostByModelId returns the first NONZERO cost
// walking this list, so a reordering changes which vendor wins a duplicate id.
const priorityLine = must(
  source.match(/^const COST_VENDOR_PRIORITY = (\[.*\]);$/m),
  "COST_VENDOR_PRIORITY not found — generated format changed",
);
const costVendorPriority: string[] = JSON.parse(priorityLine[1]);
if (costVendorPriority.length === 0) throw new Error("empty COST_VENDOR_PRIORITY");

// Aliases: same upstream function the TS generator uses, then verified against
// the committed artifact so a divergence fails the build instead of shipping.
const aliases = deriveJawcodeAliases();
const committedAliasBlock = must(
  source.match(/^const PROVIDER_ALIASES: Record<string, string> = (\{[\s\S]*?\}) as const;$/m),
  "PROVIDER_ALIASES not found — generated format changed",
);
const committedAliases: Record<string, string> = JSON.parse(committedAliasBlock[1]);
const aliasKeys = Object.keys(aliases).sort();
const committedKeys = Object.keys(committedAliases).sort();
if (aliasKeys.join(",") !== committedKeys.join(",")) {
  throw new Error(`alias key set drift: derived=${aliasKeys.length} committed=${committedKeys.length}`);
}
for (const key of aliasKeys) {
  if (aliases[key] !== committedAliases[key]) {
    throw new Error(`alias value drift for ${key}: derived=${aliases[key]} committed=${committedAliases[key]}`);
  }
}

/** JS String() is already shortest-round-trip; Go parses these to the identical
 *  float64. Rounding here would shift the value by 1 ULP. */
function goFloat(value: number): string {
  const text = String(value);
  return text.includes(".") || text.includes("e") || text.includes("E") ? text : `${text}`;
}

const quote = (value: string) => JSON.stringify(value);

const lines: string[] = [];
lines.push("// Code generated by scripts/generate-jawcode-go.ts. DO NOT EDIT.");
lines.push("//");
lines.push("// Mirrors src/generated/jawcode-model-metadata.ts — the same committed bytes the");
lines.push("// TypeScript runtime reads — so Go and TS price identically. Regenerate with");
lines.push("// `bun run generate:jawcode:go` whenever that file changes.");
lines.push("package jawcode");
lines.push("");
lines.push("// Cost is USD per 1M tokens, matching the jawcode catalog convention.");
lines.push("type Cost struct {");
lines.push("\tInput      float64 `json:\"input\"`");
lines.push("\tOutput     float64 `json:\"output\"`");
lines.push("\tCacheRead  float64 `json:\"cacheRead\"`");
lines.push("\tCacheWrite float64 `json:\"cacheWrite\"`");
lines.push("}");
lines.push("");
lines.push("// Cost is a pointer because the source rows carry it optionally");
lines.push("// (rowToMetadata only sets cost when all four values are present).");
lines.push("type Model struct {");
lines.push("\tProvider      string");
lines.push("\tID            string");
lines.push("\tContextWindow int");
lines.push("\tMaxTokens     int");
lines.push("\tReasoning     bool");
lines.push("\tWireModelID   string");
lines.push("\tCost          *Cost");
lines.push("}");
lines.push("");

lines.push("var providerAliases = map[string]string{");
for (const key of Object.keys(aliases).sort()) {
  lines.push(`\t${quote(key)}: ${quote(aliases[key])},`);
}
lines.push("}");
lines.push("");

lines.push("// Order matters: FindCostByModelID returns the first nonzero cost along this");
lines.push("// list, so it decides which vendor wins a model id served by several.");
lines.push("var costVendorPriority = []string{");
for (const vendor of costVendorPriority) lines.push(`\t${quote(vendor)},`);
lines.push("}");
lines.push("");

let rowCount = 0;
lines.push("var models = map[string]map[string]Model{");
for (const provider of providers) {
  const rows = listJawcodeModelMetadata(provider).slice().sort((a, b) => a.id.localeCompare(b.id));
  lines.push(`\t${quote(provider)}: {`);
  for (const row of rows) {
    rowCount++;
    const parts = [`Provider: ${quote(provider)}`, `ID: ${quote(row.id)}`];
    if (row.contextWindow != null) parts.push(`ContextWindow: ${row.contextWindow}`);
    if (row.maxTokens != null) parts.push(`MaxTokens: ${row.maxTokens}`);
    if (row.reasoning) parts.push("Reasoning: true");
    if (row.wireModelId != null) parts.push(`WireModelID: ${quote(row.wireModelId)}`);
    if (row.cost) {
      parts.push(
        `Cost: &Cost{Input: ${goFloat(row.cost.input)}, Output: ${goFloat(row.cost.output)}, ` +
        `CacheRead: ${goFloat(row.cost.cacheRead)}, CacheWrite: ${goFloat(row.cost.cacheWrite)}}`,
      );
    }
    lines.push(`\t\t${quote(row.id)}: {${parts.join(", ")}},`);
  }
  lines.push("\t},");
}
lines.push("}");
lines.push("");

lines.push(`// Bundle shape at generation time: ${providers.length} providers, ${rowCount} rows.`);
lines.push("// The tests assert these numbers so a generator regression cannot ship quietly.");
lines.push(`const generatedProviderCount = ${providers.length}`);
lines.push(`const generatedRowCount = ${rowCount}`);
lines.push("");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n") + "\n");
// Emit gofmt-clean output so `gofmt -l` stays quiet in CI and the artifact is
// byte-stable across regenerations.
try {
  execFileSync("gofmt", ["-w", outPath], { stdio: "inherit" });
} catch (error) {
  throw new Error(`gofmt failed on the generated bundle: ${String(error)}`);
}
console.log(`wrote ${outPath}: ${providers.length} providers, ${rowCount} rows, ${Object.keys(aliases).length} aliases, ${costVendorPriority.length} vendor-priority entries`);
